/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "LightV UI",
  "description": "一个好用的 UI 框架",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "LightV UI",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4d58773e",
      "path": "/"
    },
    {
      "title": "组件",
      "frontmatter": {},
      "regularPath": "/components/",
      "relativePath": "components/README.md",
      "key": "v-744750e1",
      "path": "/components/"
    },
    {
      "title": "快速上手",
      "frontmatter": {},
      "regularPath": "/get_started/",
      "relativePath": "get_started/README.md",
      "key": "v-acdea8ce",
      "path": "/get_started/"
    },
    {
      "title": "按钮",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "'",
        "7": "b",
        "8": "u",
        "9": "t",
        "10": "t",
        "11": "o",
        "12": "n",
        "13": "'"
      },
      "regularPath": "/components/button.html",
      "relativePath": "components/button.md",
      "key": "v-3e5c0dea",
      "path": "/components/button.html"
    },
    {
      "title": "安装",
      "frontmatter": {},
      "regularPath": "/install/",
      "relativePath": "install/README.md",
      "key": "v-7a7f2913",
      "path": "/install/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "文档",
        "link": "/install/"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/Light-V-1995/LightV-UI/tree/master"
      }
    ],
    "sidebar": [
      {
        "title": "入门",
        "children": [
          "/install/",
          "/get_started/"
        ]
      },
      {
        "title": "组件",
        "children": [
          "/components/button"
        ]
      }
    ]
  }
}